---
- name: repos | epel repo if set
  dnf:
    name: epel-release
  when: repos_epel

- name: repos | add custom repos if set
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "/etc/yum.repos.d/{{ item.name }}.repo"
    baseurl: "{{ item.baseurl }}"
    mirrorlist: "{{ item.mirrorlist | default(omit) }}"
    enabled: "{{ item.enabled | default('yes') }}"
    state: "{{ item.state | default('present') }}"
    gpgcheck: "{{ item.gpgcheck | default('no') }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    includepkgs: "{{ item.includepkgs | default(omit) }}"
  loop: "{{ repos_custom }}"
  register: repos_set
  when: repos_custom | length > 0

- name: repos | yum-clean-metadata
  shell: yum clean metadata
  when: repos_set.changed or epel_result is defined
  args:
    warn: false
