---
- name: sysctl | ensure sysctl configuration are applied
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ item.file }}"
    reload: true
  loop: "{{ sysctl_config }}"
