---
- name: time | set timezone
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: true

- name: time | ensure chrony is installed
  dnf:
    name: chrony
    state: latest

- name: time | ensure chrony is running and enabled
  systemd:
    name: chronyd
    state: started
    enabled: true
  tags: molecule-notest
